version: '3.6'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command: mongod --auth --smallfiles  --logpath=/dev/null # --quiet

