version: '3.4'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles
