// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface GetActions {
    actions:                 Action[];
    last_irreversible_block: number;
}

export interface Action {
    global_action_seq:  number;
    account_action_seq: number;
    block_num:          number;
    block_time:         string;
    action_trace:       ActionTrace;
}

export interface ActionTrace {
    receipt:         Receipt;
    act:             Act;
    elapsed:         number;
    cpu_usage:       number;
    console:         string;
    total_cpu_usage: number;
    trx_id:          string;
    inline_traces:   any[];
}

export interface Act {
    account:       string;
    name:          string;
    authorization: Authorization[];
    data:          Data;
    hex_data:      string;
}

export interface Authorization {
    actor:      string;
    permission: string;
}

export interface Data {
    poster:             string;
    post_uuid:          string;
    content:            string;
    reply_to_poster:    string;
    reply_to_post_uuid: string;
    certify:            number;
    json_metadata:      string;
}

export interface Receipt {
    receiver:        string;
    act_digest:      string;
    global_sequence: number;
    recv_sequence:   number;
    auth_sequence:   Array<Array<number | string>>;
    code_sequence:   number;
    abi_sequence:    number;
}
